### ISSUE TITLE
[BUG] Images shift upwards when you delete an email.

### ISSUE THREAD

**Issue by jrimmer-bendhealth** [noam-sc/thunderbird-auto-profile-picture#14]
First: Great plugin; I wish this functionality was in Thunderbird core.

I have a massive inbox, and so there is a delay between when I delete or move an email and when the move/delete actually occurs on the server. Thunderbird helpfully marks these emails as deleted by striking through the text in Cards View, prior to removing them from the display.

auto-profile-picture is shifting the images up before the actual email has been removed. See attached screenshots. The first screenshot is prior to deletion, the second is after marking the email as deleted; notice how the "b" icon has been replaced with the Github Octocat icon.

The workaround has been to click the "Get Messages" button; that re-synchronizes everything *usually* and it works again.

Ideally, the icons should stick to whatever emails they're attached to.

Before Delete:
<img width="356" height="269" alt="Image" src="https://github.com/user-attachments/assets/c3cf371b-0f35-4f57-9054-c26d3662f987" />

After Delete:
<img width="360" height="274" alt="Image" src="https://github.com/user-attachments/assets/3222ab81-f180-402d-803c-d893732e8c52" />

**Comment by goobta** [comment]
Hi @jrimmer-bendhealth

I filed a similar bug, but for archiving instead of deleting:
https://github.com/noam-sc/thunderbird-auto-profile-picture/issues/13

I might try to take a crack at it this weekend or next. I'll update bugs with progress if you want to try it out :)

**Comment by noam-sc** [comment]
Thanks for reporting this issue!
This "striking emails" behavior isn’t something I was aware of when there are server delays. 

I believe this is a different bug than #13 because, in this case, icons are shifting when they shouldn't (unlike #13 where icons are not shifting when they should). I'll investigate it.

**Comment by noam-sc** [comment]
Hey @jrimmer-bendhealth , thanks for your patience!

I've fixed the issue, but since I don't experience the email delay behavior you reported, I'd appreciate it if you could test the fix for me.
You can download it here: https://github.com/noam-sc/thunderbird-auto-profile-picture/actions/runs/18144322983/artifacts/4148502404
To install it, just unzip it and import the XPI to Thunderbird Add-ons settings page.

Thanks!

**Comment by jrimmer-bendhealth** [comment]
I removed the add-on, added yours, and tried it. No, I'm still seeing the issue. :(

**Comment by jrimmer-bendhealth** [comment]
Is there some further debug data I could pass on?

**Comment by jrimmer-bendhealth** [comment]
I went to my junk mail box and deleted one email. 

I've got a screenshot showing the cards, where you can see 
1. I sort oldest first
2. The deleted email picked up the icon that should be for the subsequent one (and _that_ one picked up the icon for the one below it).

deleted.xml is the DOM for the deleted (strikethrough) email; next-email.xml is the DOM for the one below it.

And I've censored names/emails to protect the guilty.

[deleted.xml](https://github.com/user-attachments/files/22645424/deleted.xml)
[next-email.xml](https://github.com/user-attachments/files/22645423/next-email.xml)
<img width="340" height="141" alt="Image" src="https://github.com/user-attachments/assets/63910c85-88f8-4c85-be80-da929e6e0b0c" />

**Comment by jrimmer-bendhealth** [comment]
It's worth adding... since my example is for two senders who didn't have proper icons... that the _colors_ shifted upwards. That is to say -- K.C.'s icon was oklch(0.87 0.052 236.57) previously, and that _color_ also moved up, along with the letters.
